### ISSUE TITLE
Could you lend me a hand? :D

### ISSUE THREAD

**Issue by Tungz74** [woctezuma/steam-reviews#2]
Hey, woctezuma,

I actually don't know if this is the right place to ask the questions I'm about to, but I don't really know how to use this platform yet and I couldn't find your e-mail here. So I'm sorry if I'm misusing it.

I'm currently working on a research on a game called This War of Mine, so I was looking for some software that could help me downloading its reviews on steam. I didn't' find it, but Google took me to your work! I would like to ask if you know how I could do it.

I've read the description of steam-reviews and it sounded like that's what I'm looking for, but I didn't manage to make it work — probably my programming skills are not good enough haha

Thank you very much for your time and attention (:

**Comment by woctezuma** [comment]
Hi,

This repository grew out of control, with different side projects, so it can be confusing for newcomers. Moreover, some of the functions might not work after [SteamSpy API was very recently closed](https://www.eurogamer.net/articles/2018-04-11-why-steam-spy-has-to-close-from-the-creator-himself).

That being said, what you need to download Steam reviews should be [in this file](https://github.com/woctezuma/steam-reviews/blob/master/download_reviews.py). By the look of it, the imports are very standard, and SteamSpy API is not used, so the functions should still work fine.

So let us assume you have installed Python 3.X, and `pip install requests`. You download the files:
- [`download_reviews.py`](https://github.com/woctezuma/steam-reviews/blob/master/download_reviews.py)
- [`appids.py`](https://github.com/woctezuma/steam-reviews/blob/master/appids.py),
Put both in a folder. In order to avoid downloading reviews for games which I use as references for my other algorithms, edit [the end of `download_reviews.py`](https://github.com/woctezuma/steam-reviews/blob/c364aaeafddc5404e4659228dd012ac61dfd9c45/download_reviews.py#L203) to change from:
`    download_reference_hidden_gems_as_well = True`
to
`    download_reference_hidden_gems_as_well = False`

Now, you want to create a text file `idlist.txt` with the appIDs of the games you are interested in. In your case, the appID of the game you are interested in is "282070", as you can infer from [the URL of its page on the Steam store](http://store.steampowered.com/app/282070/This_War_of_Mine/), so the text file contains only one line with 282070.

You should be able to run the script now by calling `python download_reviews.py`: you will get 150 reviews every 5 minutes because Steam API is rate-limited.

**Comment by Tungz74** [comment]
That's good news, Wok :D
I'm gonna try it.
Thank you very much!

**Comment by woctezuma** [comment]
There are 43,346 reviews, so you will need roughly 1h15m to download everything.

Since I was interested in smaller games, I only save reviews once a game is completely processed. In your case, since there is only one big game, reviews will only be saved once the process is finished.

**Comment by Tungz74** [comment]
It worked perfectly fine! :D
Thanks a lot 💃

**Comment by woctezuma** [comment]
Super. Thanks for the feedback! :)

**Comment by woctezuma** [comment]
In case someone else ends up here in the future, I have copied the required code to [a distinct Github repository](https://github.com/woctezuma/download-steam-reviews) to keep it simple.
